config/routes.rb
Rails.application.routes.draw do
  resources :recipes

   root 'recipes#index'

end

app/models/cuisine.rb
class Cuisine < ActiveRecord::Base
  has_many :recipes
end

app/models/food_preference.rb
class FoodPreference < ActiveRecord::Base
  has_many :recipes
end

app/models/food_type.rb
class FoodType < ActiveRecord::Base
  has_many :recipes
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :food_type
  belongs_to :cuisine
  belongs_to :food_preference


  DIFFICULTY = %w(Easy Medium Hard)

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:title, :cooking_time, :difficulty_level, :food_type_id, :food_preference_id, :cuisine_id, :ingredients, :procedure)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Recetas</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :cooking_time %><br>
    <%= f.text_field :cooking_time %>
  </div>
  <div class="field">
    <%= f.label :difficulty_level %><br>
     <%=f.select :difficulty_level, Recipe::DIFFICULTY,{} , :class => "form-control"%> 
 </div>
  <div class="field">
    <%= f.label :food_type_id %><br>
    <%= f.select(:food_type_id, options_from_collection_for_select(FoodType.all, :id, :name), {:prompt => 'Please Choose'}, :class => "form-control") %>
  </div>
  <div class="field">
    <%= f.label :food_preference_id %><br>
    <%= f.select(:food_preference_id, options_from_collection_for_select(FoodPreference.all, :id, :name), {:prompt => 'Please Choose'}, :class => "form-control")  %>
  </div>
  <div class="field">
    <%= f.label :cuisine_id %><br>
    <%= f.select(:cuisine_id, options_from_collection_for_select(Cuisine.all, :id, :name), {:prompt => 'Please Choose'}, :class => "form-control") %>
  </div>
  <div class="field">
    <%= f.label :ingredients %><br>
    <%= f.text_area :ingredients %>
  </div>
  <div class="field">
    <%= f.label :procedure %><br>
    <%= f.text_area :procedure %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<h1>Listing recipes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Cooking time</th>
      <th>Difficulty level</th>
      <th>Food type</th>
      <th>Food preference</th>
      <th>Cuisine</th>
      <th>Ingredients</th>
      <th>Procedure</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= recipe.title %></td>
        <td><%= recipe.cooking_time %></td>
        <td><%= recipe.difficulty_level %></td>
        <td><%= recipe.food_type.name %></td>
        <td><%= recipe.food_preference.name %></td>
        <td><%= recipe.cuisine.name %></td>
        <td><%= recipe.ingredients %></td>
        <td><%= recipe.procedure %></td>
        <td><%= link_to 'Show', recipe %></td>
        <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
        <td><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipe', new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @recipe.title %>
</p>

<p>
  <strong>Cooking time:</strong>
  <%= @recipe.cooking_time %>
</p>

<p>
  <strong>Difficulty level:</strong>
  <%= @recipe.difficulty_level %>
</p>

<p>
  <strong>Food type:</strong>
  <%= @recipe.food_type_id %>
</p>

<p>
  <strong>Food preference:</strong>
  <%= @recipe.food_preference_id %>
</p>

<p>
  <strong>Cuisine:</strong>
  <%= @recipe.cuisine_id %>
</p>

<p>
  <strong>Ingredients:</strong>
  <%= @recipe.ingredients %>
</p>

<p>
  <strong>Procedure:</strong>
  <%= @recipe.procedure %>
</p>

<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>